//
// STARSpan project
// Carlos A. Rueda
// starspan_gen_envisl - generates envi output
// $Id$
//

#include "starspan.h"           
#include "traverser.h"       

#include <stdlib.h>
#include <string.h>
#include <assert.h>

// used to write the number of extracted pixels in header since this is
// done in two passes: the first one in which the number of
// is unknown, and a second one to update it.
#define LINES_WIDTH 8



/**
  * Populates the envi file
  */
class EnviSlObserver : public Observer {
public:
	// true=image, false=spectral library 
	bool envi_image;
	int typeSize;
	int numBands;
	FILE* data_file;
	FILE* header_file;
	FILE* class_file;
	const char* select_fields;
	
	OGRFeature* currentFeature;
	int numSpectra;	
	long update_offset;
	
	/**
	  * Initializes the header.
	  */
	EnviSlObserver(bool image, int bands, FILE* df, FILE* hf, FILE* cf, const char* select_fields_)
	: envi_image(image), numBands(bands), 
	  data_file(df), header_file(hf), class_file(cf),
	  select_fields(select_fields_)
	{
		numSpectra = 0;
		
		//
		// header varies depending on type of file to create.
		//
		
		// common part
		fprintf(header_file,
			"ENVI\n" 
			"description = {Generated by starspan}\n"
		);
		
		if ( envi_image ) {
			// samples:  value will be given at end of process
			fprintf(header_file, "samples = ");
			// take current file pointer to later update this:
			update_offset = ftell(header_file);
			fprintf(header_file, "%*d\n", LINES_WIDTH, 0);
			
			// lines and bands
			fprintf(header_file, "lines = 1\n");
			fprintf(header_file, "bands = %d\n", numBands);
			
			// file type
			fprintf(header_file, "file type = ENVI Standard\n");
		}
		else {
			// spectral library.
			
			// samples:
			fprintf(header_file, "samples = %d\n", numBands);
			
			// lines:  value will be given at end of process
			fprintf(header_file, "lines = ");
			// take current file pointer to later update number of lines:
			update_offset = ftell(header_file);
			fprintf(header_file, "%*d\n", LINES_WIDTH, 0);
			
			// bands (for a spectral library is 1)
			fprintf(header_file, "bands = 1\n");
			
			// file type
			fprintf(header_file, "file type = ENVI Spectral Library\n");
		}			
		
		// common:
		
		// header offset and file type
		fprintf(header_file, "header offset = 0\n");
		
		// data type    PENDING to generalize
		fprintf(header_file, "data type = 2\n");
		
		// interleave and sensor type
		fprintf(header_file, "interleave = bip\n");
		fprintf(header_file, "sensor type = Unknown\n");
		
		// byte order (Intel)  PENDING to generalize
		fprintf(header_file, "byte order = 0\n");

		/////////////////////////////////////////////////////////
		// wavelength values:
		// NOTE: ad hoc values: unfortunately GDAL does not provide a way
		// to access the wavelength meta-attribute from source dataset.
		// A solution for this is PENDING.
		fprintf(header_file,
			"wavelength = {"
		);
		for ( int i = 0; i < numBands; i++ ) {
			if ( i > 0 ) fprintf(header_file, ",");
			fprintf(header_file, "\n  %d", i+1);
		}
		fprintf(header_file, "\n}\n");
		
		if ( !envi_image ) {    // spectral library
			// spectra names:
			fprintf(header_file,
				"spectra names = {"
			);
		}
		
		currentFeature = NULL;
	}
	
	/**
	  * nothing is done.
	  */
	~EnviSlObserver() {
	}
	

	/**
	  *
	  */
	void init(GlobalInfo& info) { 
		typeSize = info.band.typeSize;
	}
	

	/**
	  * Used here to update currentFeature
	  */
	void intersectionFound(OGRFeature* feature) {
		currentFeature = feature;
	}

	
	/**
	  * Adds a spectrum to the output file.
	  * Each spectrum take a name with the following structure:
	  *      FID:col:row
	  */
	void addPixel(TraversalEvent& ev) { 
		int col = ev.pixel.col;
		int row = ev.pixel.row;
		void* band_values = ev.bandValues;
		
		//
		// write bands to binary file:
		//
		if ( (size_t) numBands != fwrite(band_values, typeSize, numBands, data_file) ) {
			fprintf(stderr, "Couldn't write pixel\n");
			exit(1);
		}
		
		
		if ( !envi_image ) {    // spectral library
			// add spectrum name to header
			char spectrum_name[1024];
			sprintf(spectrum_name, "%ld:%d:%d", currentFeature->GetFID(), col, row);
			if ( numSpectra > 0 )
				fprintf(header_file, ",");
			fprintf(header_file, "\n  %s", spectrum_name);
		}
		
		///////////////////////////////////////////////
		// add class fields if so indicated
		if ( class_file && select_fields ) {
			int num_fields = 0;
			char buff[strlen(select_fields) + 1];
			strcpy(buff, select_fields);
			for ( char* fname = strtok(buff, ","); fname; fname = strtok(NULL, ",") ) {
				if ( num_fields++ )
					fprintf(class_file, ", ");
				
				const int i = currentFeature->GetFieldIndex(fname);
				if ( i < 0 ) {
					fprintf(stderr, "\n\tField `%s' not found\n", fname);
					exit(1);
				}
				OGRFieldDefn* poField = currentFeature->GetFieldDefnRef(i);
				OGRFieldType ft = poField->GetType();
				switch(ft) {
					case OFTString: {
						const char* str = currentFeature->GetFieldAsString(i);
						fprintf(class_file, "%s", str);
						break;
					}
					case OFTInteger: { 
						int val = currentFeature->GetFieldAsInteger(i);
						fprintf(class_file, "%d", val);
						break;
					}
					case OFTReal: { 
						double val = currentFeature->GetFieldAsDouble(i);
						fprintf(class_file, "%f", val);
						break;
					}
					default:
						fprintf(stderr, "addPixel: expecting: "
								"OFTString, OFTInteger, or OFTReal \n");
						exit(2);
				}
			}
			fprintf(class_file, "\n");
		}		 
		
		numSpectra++;
	}
	
	/**
	  * Finishes the header file
	  */
	void _end() {
		if ( !envi_image ) {    // spectral library
			// close spectra names section:
			fprintf(header_file, "\n}\n");
		}
		// update number of lines or samples:
		fseek(header_file, update_offset, SEEK_SET);
		fprintf(header_file, "%*d", LINES_WIDTH, numSpectra);
	}
};


/**
  * implementation
  */
int starspan_gen_envisl(
	Raster* rast, 
	Vector* vect,
	const char* select_fields,
	const char* envisl_name,
	bool envi_image
) {
	// output files
	char data_filename[1024];
	sprintf(data_filename, "%s.img", envisl_name);
	char header_filename[1024];
	sprintf(header_filename, "%s.hdr", envisl_name);
	
	FILE* data_file = fopen(data_filename, "w");
	if ( !data_file ) {
		fprintf(stderr, "Couldn't create %s\n", data_filename);
		return 1;
	}

	FILE* header_file = fopen(header_filename, "w");
	if ( !header_file ) {
		fclose(data_file);
		fprintf(stderr, "Couldn't create %s\n", header_filename);
		return 1;
	}
	
	FILE* class_file = NULL;
	if ( select_fields ) {
		char class_filename[1024];
		sprintf(class_filename, "%s_classes.txt", envisl_name);
		class_file = fopen(class_filename, "w");
		if ( !class_file ) {
			fclose(header_file);
			fclose(data_file);
			fprintf(stderr, "Couldn't create %s\n", class_filename);
			return 1;
		}
	}
	
	
	int bands;
	rast->getSize(NULL, NULL, &bands);
	EnviSlObserver obs(envi_image, bands, data_file, header_file, class_file, select_fields);	
	Traverser tr(rast, vect);
	tr.setObserver(&obs);
	
	tr.traverse();
	
	obs._end();
	
	fclose(header_file);
	fclose(data_file);
	if ( class_file )
		fclose(class_file);
	fprintf(stdout, "numSpectra = %d\n", obs.numSpectra);
	fprintf(stdout, "envisl finished.\n");

	return 0;
}
		


